'use client';

import {
  AlertCircle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LucideProps,
  MapPin,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  Info,
  AlertTriangle,
} from 'lucide-react';
import { ComponentProps, ForwardRefExoticComponent, RefAttributes } from 'react';

export type IconProps = ComponentProps<'svg'> & {
  size?: number;
};

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  alert: AlertCircle,
  check: Check,
  file: File,
  fileText: FileText,
  image: Image,
  twitter: Twitter,
  info: Info,
  mapPin: MapPin,
};
